[server]
headless = true

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#00E5FF"
backgroundColor = "#0a0e27"
secondaryBackgroundColor = "#001a33"
textColor = "#00E5FF"
font = "sans serif"
